# Generated by Django 5.2.3 on 2025-06-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Test Company', max_length=255)),
                ('logo_url', models.URLField(default='https://play.google.com/store/apps/details?id=com.nse.nseindia')),
                ('price_band', models.CharField(default='100-120', max_length=50)),
                ('issue_type', models.CharField(default='Book Built', max_length=50)),
                ('issue_size', models.CharField(default=1000, max_length=50)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
